import { Card } from '../components/MotoristaCard'
import { MainContainer, Body } from '../styles/pages'

export default function Home() {
  return (
    <MainContainer>
      <Body>
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />

        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
        <Card
          name="carlos"
          profileURL="/motorista.jpg"
          backGroundURL="/caminhao.png"
        />
      </Body>
    </MainContainer>
  )
}
